#!/bin/bash
# converts the passed-in svgs to tiff and ico
# based on this: http://stackoverflow.com/a/23688878/300213

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 svg1 [svg2 [...]]"
    exit 0
fi

temp=$(mktemp -d)
declare -a res=(8 16 24 32 48 64 128 256 512)
for f in $*; do
    mkdir -p $temp/$(dirname $f)
    for r in "${res[@]}"; do
        inkscape -z -e $temp/${f}${r}.png -w $r -h $r $f
        mkdir -p ${r}x${r}
        cp $temp/${f}${r}.png ${r}x${r}/$(basename $f .svg).png
    done
    resm=( "${res[@]/#/$temp/$f}" )
    resm=( "${resm[@]/%/.png}" )
    convert "${resm[@]}" ${f%%.*}.ico
done
rm -rf $temp