unit gui_gtk2_glyphs;

{$mode objfpc}{$H+}

interface
{$IFDEF LCLGTK2}

uses
  Classes, SysUtils, Graphics, gui_glyphs, gtk2, LCLType;

const IconMap: array[TStewButtonGlyph] of String =
(
// https://docs.google.com/spreadsheets/d/1HavJQRPpMuq-N0GoN1wJR-9KEGXpKy3-NEPpZZkUGJY/pub?output=html
'image-missing',
'document-new',
'document-open',
'preferences-system',
'document-properties',
'application-exit',
'help-about',
'document-new',
'document-new',
'gtk-edit', // TODO: migration guide does not provide an appropriate icon.
'go-up',
'go-down',
'edit-delete',
'window-close',
'document-save',
'view-refresh',
'document-new',
'gtk-edit',
'document-new',
'gtk-edit',
'list-add',
'list-add',
'list-add',
'list-add',
'list-add'
);

function Gtk2GetStewButtonIcon(aID: TStewButtonGlyph; aRequestedSize: Longint; out oBitmap: HBitmap; out oMask: HBitmap): Boolean;

{$ENDIF}
implementation
{$IFDEF LCLGTK2}

uses
  Gtk2Def,
  gdk2pixbuf,
  Gtk2Proc,
  Gtk2Int,
  gdk2,
  glib2;

function Gtk2GetStewButtonIcon(aID: TStewButtonGlyph; aRequestedSize: Longint; out oBitmap: HBitmap; out oMask: HBitmap): Boolean;
var
  GDIObj: PGDIObject;
  StockName: PChar;
  //Style: PGtkStyle;
  //IconSet: PGtkIconSet;
  lPixbuf: PGDKPixbuf;
  lIconTheme: PGtkIconTheme;
  lPError: PGError;
  //lState: TGtkStateType;
begin
  result := false;
  StockName := PChar(IconMap[aID]);

  {
  The old way:
  Style := GetStyle(lgsButton);

  if (Style = nil) or (not GTK_IS_STYLE(Style)) then
  begin
    oBitmap := 0;
    oMask := 0;
    Exit;
  end;

  IconSet := gtk_style_lookup_icon_set(Style, StockName);

  if (IconSet = nil) then
  begin
    oBitmap := 0;
    oMask := 0;
    Exit;
  end;

  if aDisabled then
     lState := GTK_STATE_INSENSITIVE
  else
     lState := GTK_STATE_NORMAL;

  lPixbuf := gtk_icon_set_render_icon(IconSet, Style,
      GTK_TEXT_DIR_NONE, lState, GTK_ICON_SIZE_BUTTON, GetStyleWidget(lgsbutton), nil);}
  lIconTheme := gtk_icon_theme_get_default;
  lPError := nil;
  lPixbuf := gtk_icon_theme_load_icon(lIconTheme,StockName,aRequestedSize,GTK_ICON_LOOKUP_USE_BUILTIN,@lPError);

  if lPixbuf <> nil then
  begin
    GDIObj := Gtk2Widgetset.NewGDIObject(gdiBitmap);
    with GDIObj^ do
    begin
      GDIBitmapType := gbPixbuf;
      visual := gdk_visual_get_system();
      gdk_visual_ref(visual);
      colormap := gdk_colormap_get_system();
      gdk_colormap_ref(colormap);
      GDIPixbufObject := lPixbuf;
    end;

    oBitmap := HBitmap({%H-}PtrUInt(GDIObj));
  end
  else
  begin
    raise Exception.Create('Error loading stock icon: ' + lPError^.message);
    oBitmap := 0;
  end;

  oMask := 0;
  Result := True;
end;

procedure ListIcons;
var
  lList: PGList;
  lItem: PGList;
  lIconTheme: PGtkIconTheme;
begin
  lIconTheme := gtk_icon_theme_get_default;
  lList := gtk_icon_theme_list_icons(lIconTheme,nil);
  try
    lItem := lList;
    while lItem <> nil do
    begin
      WriteLn(PChar(lItem^.data));
      g_free(lItem^.data);
      lItem := lItem^.next;
    end;

  finally
    g_list_free(lList);
  end;

end;

initialization
// TODO: When I'm looking for icons...  ListIcons;
{sunny
planets
package
stock_bottom
config-language
dialog-ok
banshee-1
input-gaming
gnome-mime-image
gtk-underline
document-properties
go-first
gnome-mplayer
gtk-indent-ltr
gnome-samegnome
gnome-mime-text-x-chdr
configuration_section
notepad-48
nm-tech-gprs
multisystem-drweb
kompozer
face-worried
alltray
mail-messages-symbolic
aptdaemon-action-updating-cache
image-x-tga
view-restore
multisystem-deli
audio-volume-muted-panel
weather-few-clouds-night-130
network-idle-symbolic
skype_invisible
evolution-mail
openofficeorg-impress
text-x-makefile
gksu-debian
unetbootin
multisystem-ar
multisystem-apodio
multisystem-shilaos
nk.ntm_on
folder-remote-symbolic
application-vnd.openxmlformats-officedocument.presentationml.slideshow
gnome-mime-application-x-java-archive
recoll
multisystem-it
document-save-as-symbolic
gtk-spell-check
package-upgrade
empathy-available
tap-create
go-jump-rtl-symbolic
package_multimedia
01A0_clockit_en.0
gnome-dev-disc-cdrw
weather-clear-night-170
xfsm-reboot
weather-few-clouds-night-120
gnome-terminal
network-cellular-signal-ok-symbolic
krfb
multisystem-en_GB
wireshark
multisystem-poseidon
xfce-man
applets-screenshooter
multisystem-rescue
multisystem-hr
multisystem-hu
multisystem-igelle
gconf-editor
folder-wine
xfpm-mouse-100
gnome-mime-text-x-sh
gnome-help
thunar
multisystem-liveusb
multisystem-imagicos
dialog-password-symbolic
openofficeorg3.0-math
weather-clear-night-160
libreoffice3-base
xfce4-mcs-manager
logo
gtk-redo-ltr
multisystem-update
weather-few-clouds-night-110
multisystem-he
application-x-java-archive
xfpm-phone-100
1FEA_ClockIt-Online_CreateAccount.0
1CD8_rundll32.0
multisystem-joldzic
openjdk-7
7765_winebrowser.0
openjdk-6
appointment-soon
redo
xfpm-ups-100
gtk-home
stock_bookmark
xchat
opera-browser
debian-swirl
gtk-justify-fill
user-idle
A35F_hh.0
itunes
gnome-apt
multisystem-tails
xfpm-ups-080-charging
weather-clear-night-150
krdc
weather-few-clouds-night-100
gpm-primary-100-charging
emblem-synchronizing-symbolic
multisystem-ge
weather-indicator
tap-extract
stock_view-details
nautilus-progress-info-panel
document-open-symbolic
gtk-revert-to-saved-ltr
drive-removable-media-usb
multisystem-matriux
network-vpn-acquiring-symbolic
battery-missing
application-vnd.wordperfect
ooo-writer3.0
multisystem-blankon
multisystem-fr
internet-archive
multisystem-kdelive
multisystem-hidden
system-run-symbolic
chrome-blpcfgokakmgnkcojhhkbfbldkacnbeo-Default
weather-clear-night-140
red
text-richtext
426B_autorota.0
multisystem-vyatta
multisystem-es
multisystem-forensic
multisystem-lps
text-xml
multisystem-bg
rssowl
stock_music-library
evolution-calendar
openofficeorg3-drawing
preferences-desktop-display
xfce-system-settings
multisystem-et
jockey
multisystem-en
accessories-calculator-symbolic
notification-audio-volume-high
start-here-gnome
gnome-mime-application-x-gzpostscript
hi48-app-wireshark
weather-clear-night-130
openofficeorg3.0-writer
multisystem-cs
go-previous-symbolic
stock_spam
gnome-mime-text-plain
printer-network
xfce4-weather
new-messages-red
gnome-netstatus-75-100
skype_skypeme
multisystem-map-flags
gtk-media-forward-rtl
multisystem-mythbuntu
gnome-mime-application-x-arj
radio
weather-storm-symbolic
gtk-go-forward-rtl
browser
network-wireless-connected-symbolic
multisystem-deft
network-wireless-signal-excellent-symbolic
gnome-mime-application-vnd.oasis.opendocument.image
multisystem-bodhilinux
object-flip-horizontal
abiword
multisystem-bn
gnome-mime-application-x-font-bdf
weather-clear-night-120
gnome-mime-application-ogg
gnome-searchtool
gnome-mime-application-postscript
accessories-dictionary
lock
multisystem-de
multisystem-elephant
1319_Pandoc User's Guide.0
gnome-mime-application-x-lzma
AC98_node.0
multisystem-trixbox
nm-mb-roam
notification-battery-040-plugged
trashcan_empty
gtk-media-stop
reboot-notifier
redhat-system-group
stock_refresh
gnome-dev-mouse-ball
dropboxstatus-logo
gsm-3g-full-secure
dialog-information-symbolic
gnome-mime-application-vnd.rn-realmedia-vbr
gpm-primary-charged
kpackage
network-wireless-signal-weak-symbolic
battery-low-charging-symbolic
document-revert-rtl
folder_download
player_eject
gnome-mime-application-wordperfect
weather-clear-night-110
gdu-mount
xfce-schedule
folder-pictures-symbolic
network-server-symbolic
virtualbox-vhd
media-playback-start-symbolic
redhat-tools
nm-tech-evdo
multisystem-ca
multisystem-molinux
chrome-app-list
gnome-monitor
banshee
gkdebconf
multisystem-gparted
multisystem-papug
multisystem-vlos
gnome-session
application-vnd.oasis.opendocument.spreadsheet-template
go-bottom-symbolic
gnome-mime-application-x-bittorrent
multisystem-darkracer
media-seek-backward-rtl-symbolic
stock_smiley-2
multisystem-fedora
application-certificate
stock_smiley-5
kpresenter_kpr
weather-clear-night-100
emacs23
libreoffice-database
stock_keyring
stock_smiley-8
exit
user-available-panel
stock_volume-min
stock_smiley-7
stock_smiley-6
package_system
stock_smiley-4
stock_smiley-3
system-switch-user
empty
media-video
gnome-mime-application-x-theme
stock_smiley-1
gnome-sound-properties
multisystem-tinyme
music-library
emerald-theme-manager-icon
jamendo
preferences-system-symbolic
presence_unknown
display
volume-knob
gnote
gnome-dev-dvd-alt
media-seek-backward
stock_dialog-warning
libreoffice3-draw
gdu-emblem-lvm-vg
go-first-rtl-symbolic
notification-audio-volume-off
ooo-printeradmin
application-vnd.ms-excel.sheet.macroEnabled.12
audio-volume-muted
multisystem-unity
edit-urpm-sources
previous
gnome-mime-video-x-ms-asf
user-info-symbolic
package-install
jpg
multisystem-ipcop
gtk-cdrom
xfpm-keyboard-060
lpi-help
gnome-joystick
starred
player_pause
applications-multimedia
ksnapshot
stock_notes
applications-science
emblem-videos-symbolic
phone-motorola-droid
rpmdrake
package-supported
A762_.0
multisystem-fusion
stock_lock-open
gnome-dev-disc-dvdram
bottom
stock_mail-open
xfce-filemanager
firefox
multisystem-netrunner
folder-system
multisystem-mcnlive
notification-gpm-battery-080-charging
mozo
tomboy-32
multisystem-kduxp
multisystem-siduction
VBox
lazarus
libreoffice-oasis-database
multisystem-menuetos
xfce-wm-unshade
abiword_48
multisystem-scientific
goldendict
edit-cut
virtualbox-vdi
reload
reload_page
ooo-impress
application-x-flash-video
stock_about
drive-optical
classviewer-namespace
preferences-system-network
libreoffice-base
0000_.8224
list-remove
gnome-mouse-properties
gtk-stop
gnome-mime-application-x-tex
nfs
stock_text_right
gtk-save
media-skip-backward-symbolic
application-vnd.sun.xml.writer
gtk-italic
gtk-go-back-ltr
go-home
applications-utilities
gnome-mime-text-x-vcard
gproject-source
gnome-dev-unknown-1394
media-import-audio-cd
media-zip
text-htmlh
gtk-add
gtk-zoom-fit
nm-device-wired-secure
libreoffice-spreadsheet
forward
gnome-dev-printer-new
nk.ntm_off
multisystem-blenderboot
multisystem-karoshi
multisystem-zh_CN
tomboy-16
stock_weather-few-clouds
gdu-encrypted-unlock
nm-signal-75
stock_certificate
application-x-arc
multisystem-Jolicloud
object-select-symbolic
stock_volume-med
multisystem-guadalinex
accessories-character-map
format-text-direction-ltr
exec
mail_new
gtk-remove
xfpm-keyboard-030
notification-gpm-battery-charged
multisystem-freenas
gnome-mime-application-vnd.sun.xml.impress
openofficeorg3-calc
stock_print
gnome-mime-application-zip
package-available-locked
input-touchpad
software-update-urgent-symbolic
gstreamer-properties
phone
gtk-dialog-authentication
preferences-system-network-proxy-symbolic
multisystem-teenpup
gnome-mime-application-vnd.oasis.opendocument.text
gnome-settings-keybindings
audio-x-speex+ogg
gpm-ac-adapter
shellscript
multisystem-austrumi
media-playback-start-rtl-symbolic
multisystem-antix
application-pdx
gtk-dialog-error
media-optical-dvd-r
document-new
audio-speakers
wallpaper
ubuntuone-client-updating
network-cellular-signal-good-symbolic
gnome-mime-application-vnd.stardivision.impress
application-vnd.openxmlformats-officedocument.wordprocessingml.template
notification-gpm-battery-100
multisystem-minino
gpm-primary-040-charging
image-gif
gnome-exe-thumbnailer-template
application-pdf
application-x-gzip
gucharmap
gnome-mime-application-x-font-sunos-news
nm-signal-50
application-x-desktop
xfce4-session
system-config-users
face-worried-symbolic
multisystem-linuxconsole
web-browser
ibus-setup
chrome-pjkljhegncpnkpknbcohdijeoejaedia-Default
application-vnd.oasis.opendocument.drawing-template
gnome-mime-image-jpeg
classviewer-class
multisystem-hdclone
xfpm-hibernate
battery-caution-charging-symbolic
network-workgroup
text-x-source
blank
xfce-graphics
busy
multisystem-canaima
gnome-mime-application-vnd.rn-realmedia-secure
gnome-folder
gnome-mime-application-magicpoint
stock_appointment-reminder-excl
gnome-audio
gtk-justify-right
gnome-mime-application-x-tar
filezilla
gtk-ok
image-loading
gnome-mime-text-x-c
microphone-sensitivity-high-symbolic
view-fullscreen-symbolic
xfpm-keyboard-000
folder-home
stock_first
tomboy
gnome-calendar
stock_volume-max
down
kedit
stock_open
control-center2
multisystem-grub
gnome-mime-application-x-font-ttf
go-down
security-low-symbolic
gtk-no
gnome-mime-application-vnd.openxmlformats-officedocument.presentationml.slideshow
notification-gsm-high
gnome-mime-application-x-php
mail-outbox
redhat-web-browser
filesave
application-x-zim-notebook
ccsm
chrome-nmmhkkegccagdldgiimedpiccmgmieda-Default
gnome-unknown
audio-card-symbolic
nm-signal-25
audio-x-scpls
symphytum
system-file-manager-symbolic
application-x-shellscript
multisystem-logo
stock_mic
multisystem-plop-logo
stock_volume
remove
multisystem-agreg
hdd_unmount
go-previous
multisystem-pcos
qemu-launcher-32x32
multisystem-kahelos
system-software-installer
multisystem-tangostudio
message-rfc822
media-skip-backward
multisystem-redo
multisystem-easypeasy
format-indent-less-rtl-symbolic
rightjust
audio-x-flac+ogg
javaws
media-optical-copy
gnome-mime-text-css
libreoffice-oasis-drawing-template
multisystem-snowlinux
notification-message-email
kcmsound
presence_away
mail-attachment
konsole
gnome-mime-application-rtf
kjobviewer
libreoffice-draw
openofficeorg3-impress
nm-tech-cdma-1x
multisystem-gpcservices
gpk-prefs
user-trash
gdu-emblem-lvm-lv
multimedia-player-ipod-touch
multisystem-lfs
audio-volume-low-panel
weather-clouds
mail-signed-verified
multisystem-semplice
nautilus-gdu
gnome-mime-application-x-gramps-xml
gnome-dev-removable-1394
alacarte
gdu-emblem-mp
gtk-delete
go-bottom
format-justify-center
input-mouse
office-calendar
status_lock
gtk-execute
1E64_notepad.0
pychess
stock_zoom-page
audio-volume-low
gnochm
xfce4-backdrop
gnome-mime-application-xhtml+xml
nm-signal-00
notification-battery-100-plugged
preferences-system-bluetooth
spotify-linux-48x48
gnome-fs-loading-icon
update-manager
dropboxstatus-busy
mail-unread-symbolic
application-x-ms-dos-executable
user-busy-panel
gMTPicon
gtk-media-rewind-rtl
stop
x-office-calendar
openofficeorg24-writer
multisystem-windows
tools-check-spelling
edit-paste-symbolic
object-rotate-left
audio-volume-high-symbolic
neat
folder-music
multisystem-absolute
multisystem-openmamba
mp3splt-gtk_ico
task-due
multisystem-solusos
gnome-mime-application-x-ace
libreoffice-drawing
document-save-symbolic
gnome-mime-application-vnd.sun.xml.impress.template
gnome-mime-application-vnd.oasis.opendocument.presentation
changes-allow-symbolic
gnome-dictionary
aptdaemon-download
gtk-find
applications-games
face-laugh
gnome-mime-application-x-shockwave-flash
multisystem-deepin
gnome-networktool
printer-printing
tomboy-note
system_section
mp3splt-gtk
weather-few-clouds-night
list-add
tomboy-panel
edit-copy
gnome-mime-application-x-desktop
stock_script
openofficeorg-template
player-eject
system-restart
lincity-ng
tagtool
multisystem-nexentastor
haroopad
format-indent-less
weather-showers
multisystem-damnsmall
application-x-wine-extension-citm
notification-audio-volume-muted
window_new
gnome-mime-image-tiff
badge-small
office-document
264B_cmd.0
application-x-tar
stock_terminal-reportbug
gnome-mime-text-x-python
media-optical-video-new
printer-remote
multisystem-sabily
processor
changes-prevent
xfce-ui
window-new
multisystem-windows7
multisystem-pt_BR
audio-cd-duplicate
eiciel
gtk-file
multisystem-exit
text-x-css
dvd_unmount
adobe.pdf
connect_creating
x-office-document
ac-adapter
gnome-dev-trash-empty
application-x-php
mdmsetup
multisystem-qomo
opera-widget-manager
document-print-preview
library-internet-radio
multisystem-xbmc
tap-extract-to
multisystem-grml
network-cellular-signal-weak-symbolic
gdu-check-disk
multisystem-zenwalk
krb-no-valid-ticket
folder-music-symbolic
gnome-mime-application-x-java
gvc-tone
start-here-fedora
image
drive-harddisk-system
gnome-fs-ssh
format-text-italic
media-skip-forward-rtl
gnome-mime-application-x-lhz
AdobeReader9
AdobeReader8
gnome-session-switch
chrome-apdfllckaahabafndbhieahigkjlhalf-Default
audacity32
libreoffice-extension
emacs
gproject-refresh
xfpm-battery-000-charging
stock_terminal-showborders
gnome-mime-application-vnd.sun.xml.draw
brasero
gnome-mahjongg
emblem-symbolic-link
stock_select-all
gnome-mime-application-x-lha
xterm-color_32x32
google-chrome
multisystem-VBox
application-x-wine-extension-cit
text-x-preview
gnome-do-panel
multisystem-ututo
start
xfpm-ups-missing
multisystem-sabayon
multisystem-language
xfpm-ups-100-charging
gnome-mime-application-rss+xml
icedove
gnome-mime-application-vnd.scribus
classviewer-other
gtk-sort-descending
Etermutilities-terminal
start-here-archlinux
gnome-settings-default-applications
media-dvdrw
format-justify-fill
xfce4_xicon4
xfce4_xicon3
xfce4_xicon2
xfce4_xicon1
yad
gcalctool
multisystem-framadvd
indicator-messages
multisystem-monomaxos
black
mail-send-receive-symbolic
media-memory
x-office-address-book
filefind
audio-volume-muted-symbolic
audacity16
multisystem-hybryde
multisystem-home
weather-snow-symbolic
nautilus
weather-few-clouds-night-090
vnd.fdf
gnome-mime-application-x-dvi
stock_weather-snow
stock_text_underlined
libreoffice-printeradmin
multisystem-meego
gnome-mime-image-gif
pithos-mono
gnome-dev-mouse-optical
folder-visiting
aptdaemon-resolve
mitter
stock_right
appointment-new
xfpm-ups-080
media-cdrw
gnome-control-center
media-player-banshee-stopped
network-no-route-symbolic
gtk-print-preview
gnome-mime-application-vnd.lotus-1-2-3
go-first-rtl
go-next-symbolic
stock_cell-phone
application-x-ace
network-cellular-umts-symbolic
accessories-calculator
package-available
avant-window-navigator
gpm-battery-000-charging
gnome-mime-text-x-c++
leftjust
stock_sent-mail
stock_top
ubuntu-tweak
light-gray
stock_media-rew
emblem-web
format-indent-less-symbolic
multisystem-slackel
weather-few-clouds-night-080
xfce-office
multisystem-paragon
qgis
dialog-warning-symbolic
multisystem-foresight
xfce4-clipman-plugin
multisystem-luninux
dvdisaster
multisystem-vixta
multisystem-stux
stock_media-rec
multisystem-sms
xfpm-mouse-060
chrome-coobgpohoikkiipiblmjeljniedjpjpf-Default
openofficeorg3-database
tilda
input-keyboard
edit-redo
library-podcast
gnome-netstatus-0-24
multisystem-hdd
multisystem-clonezilla
weather-fog-symbolic
gsm-3g-none
multisystem-zentyal
gnome-mime-application-x-bzip-compressed-tar
multisystem-ubuntu-server
weather-few-clouds-night-070
xfce-edit
xfpm-phone-060
palimpsest
insert-text
printer-error
openofficeorg3-math
busy2
redhat-games
virtualbox-vbox
application-vnd.openxmlformats-officedocument.presentationml.presentation
multisystem-voyager
vcard
xfpm-ups-060
trophy-gold
weather-snow
opera
notification-battery-080-plugged
system-shutdown-restart-panel
find
redhat-system_tools
mouse
aptdaemon-action-cleaning-up
gnome-mime-text-x-c++src
format-indent-more-rtl
multisystem-backbox
aptdaemon-update-cache
nm-signal-00-secure
weather-few-clouds-night-060
bookmark_add
gnome-fs-smb
connect_no
mail-send-receive
bookmark_list_add
music-player
application-x-pak
multisystem-xterm
gnome-session-halt
idle
hotwire
printer-error-symbolic
applications-development
saga
multisystem-pointlinux
wmtweaks
multisystem-usbpendrive
zoom-original-symbolic
face-embarrassed
openofficeorg3.0-printeradmin
gnome-main-menu
multisystem-uberstudent
multisystem-apple48
application-x-lhz
gnome-mime-application-x-7z-compressed
audio-cd-new
xfpm-mouse-030
network-offline-symbolic
weather-few-clouds-night-050
gnome-netstatus-tx
binary
user-invisible
libreoffice-master-document
update-notifier
gdu-eject
preferences-desktop-remote-desktop-symbolic
notification-network-wireless-low
emblem-readonly
fusion-icon
xfpm-ups-040
media-cdr
gnome-mime-application-x-bzip-compressed
21AC_autorota.0
xfce-internet
application-x-lha
xfpm-phone-030
magenta
strigi
multisystem-moblin
gnome-mime-text-x-java
umusicstore
vnd.adobe.xdp+xml
multisystem-wifiway
weather-clear-night-090
media-optical-cd
security-high
weather-few-clouds-night-040
gtwitter
authors
notification-network-wireless-none
package_graphics
bluetooth-disabled-symbolic
multisystem-os4
xterm_48x48
gpm-primary-060-charging
xfpm-phone-000
application-vnd.oasis.opendocument.master-document
gnome-mime-application-vnd.stardivision.writer
media-seek-forward
gdu-emblem-mp-component
gnome-package
weather-clear-symbolic
grub-customizer
weather-clear-night-080
go-previous-rtl-symbolic
user-trash-full
weather-few-clouds-night-030
gnome-app-install-star
xfpm-ups-020
gnome-mime-video-x-ms-wmv
zen-icon
ooo-math3.0
stock_add-bookmark
application-x-javascript
stock_outbox
battery_third_fouth
network-idle
indicator-messages-new
gnome-netstatus-rx
audio-x-generic
image-vnd.microsoft.icon
multisystem-xubuntu
gnome-mime-application-x-gramps-package
camera_unmount
bookmark-new-symbolic
system-search
gnome-mime-application-vnd.rn-realmedia
gnome-settings-font
stock_text-strikethrough
libreoffice-oasis-master-document
gnome-mixer
format-justify-right
im-chooser
start-here-ubuntu
multisystem-zorin
multisystem-mepis
multisystem-artistx
multisystem-supergamer
multisystem-ntpassword
star
media-optical-symbolic
gnome-stock-trash-full
gnome-mime-application-xfdf
multisystem-jondo
gnome-dev-zipdisk
weather-clear-night-070
computer-symbolic
xfce4-display
weather-few-clouds-night-020
weather-clear-night-symbolic
emblem-package
weather-fog
multisystem-watchdog
xfce-multimedia
folder_open
bluetooth-active
gnome-mime-text-x-c++hdr
stock_media-fwd
google-chrome-unstable
preferences-other
edit-undo-rtl-symbolic
gnome-mouse
multisystem-save
9C4B_digitaleditions.0
xfpm-mouse-000
go-top-symbolic
x-office-presentation
viewmagfit
software-update-available
stock_new-bcard
user-invisible-symbolic
dropboxstatus-idle
gnome-dev-printer
gtk-refresh
tsclient
weather-clear-night-060
office-date
gnome-dev-memory
gnome-tetravex
weather-few-clouds-night-010
stock_inbox
utilities-system-monitor
password
cab_view
gnome-color-chooser
undo
hplj1020_icon
xfpm-ups-000
bluefish
weather-clear
multisystem-estrellaroja
dropboxstatus-blank
multisystem-knoppix
battery-missing-symbolic
multisystem-blackbuntu
video-display
user-away
multisystem-kuki
weather-clear-night-050
multisystem-ipfire
harddrive
weather-few-clouds-night-000
ooo-calc2
txt2
rhythmbox-notplaying
media-playlist-repeat
gnome-mime-application-x-kspread
media-audio
multisystem-porteus
package_editors
gnome-mime-application-vnd.oasis.opendocument.graphics-template
libreoffice3-calc
gnome-dev-media-sdmmc
media-cdrom
audio-x-mpegurl
xsane
multisystem-descentos
package-purge
fonts
gnome-mime-application-x-font-afm
baobab
yast_joystick
weather-clear-night-040
wine-notepad
gnome-mime-application-xdp+xml
aptdaemon-action-installing
multisystem-element
classviewer-struct
gtkpod
leafpad
gnome-mime-application-x-shellscript
multisystem-rhinolinux
xfce4-mixer
dia_menu
edit-find-replace
contents2
screenruler
network-wireless-acquiring-symbolic
libreoffice-oasis-text-template
system-shutdown
apport
input-keyboard-symbolic
media-record
media-playback-pause
cdrom_unmount
folder_tar
84E9_ClockIt.0
multisystem-gnewsense
weather-clear-night-030
multisystem-kxstudio
multisystem-legacy
camera-photo-symbolic
audio-x-mpeg
battery-full-charging-symbolic
microphone-sensitivity-muted-symbolic
text-x-authors
stock_text_indent
xfce4-mouse
gbrainy
libreoffice-oasis-formula
edit-redo-rtl-symbolic
applications-email-panel
stock_fullscreen
keys
mozilla-firefox
package_settings
search
gnome-fs-client
youtube
ooo-base
dialog-info
media-flash
media-optical-burn
weather-clear-night-020
emblem-noread
xfce4-settings
notification-gpm-battery-080
nm-adhoc
network-wireless-signal-ok-symbolic
gtk-edit
face-smile-big
mail-folder-sent
input-touchpad-symbolic
fileprint
stock_weather-storm
computerjanitor
go-top
retext
stock_shared-to-me
AdobeReader
gnome-mime-application-x-abiword
gnome-multimedia
weather-clear-night-010
multisystem-linvo
usbpendrive_unmount
gnome-mime-text-x-javascript
image-x-portable-bitmap
gnome-computer
xfpm-primary-charged
xfpm-battery-100
gksu-root-terminal
weather-overcast-symbolic
gpm-battery-100
gtk-goto-bottom
vinagre
go-last-rtl-symbolic
gnome-mime-application-vnd.sun.xml.calc.template
application-x-java
gnome-do-icon
gufw
keepassx
folder-drag-accept
gthumb
gnome-mime-text-x-gtkrc
gnome-fs-directory
zeitgeist
application-x-cd-image
iso-image-burn
jpeg
gproject-expand
xfce-devel
display-brightness-symbolic
weather-clear-night-000
gnome-mime-x-directory-smb-share
notification-gpm-battery-060
up
gnome-mime-application-x-font-pcf
gwibber
network-receive
gnome-mime-x-install
multisystem-extix
task-past-due-symbolic
multisystem-grub2
task-due-symbolic
application-xdp+xml
multisystem-boot-repair-disk
designer-qt4
battery_low
focuswriter
key_bindings
vnd.adobe.pdx
gnome-mime-x-directory-smb-server
document-page-setup-symbolic
multisystem-uk_UA
monodoc
pstree16
minitube
folder-documents-symbolic
python3.2
gnome-mime-application-x-gnumeric
multisystem-cdlinux
musicstore_icon
battery-low
gnome-calculator
media-optical-cdr
3893_uninstall.0
pstree32
gnome-mime-text-x-credits
xfpm-battery-020-charging
mail-reply-sender
ooo-impress2
multisystem-seliso
weather-few-clouds-symbolic
application-vnd.oasis.opendocument.formula
gnome-grecord
mail-sent-symbolic
stock_last
edit-select-all-symbolic
text-x-readme
notification-gpm-battery-040
gnome-home
gksuexec-debian
gtk-network
multisystem-jabir
player_start
txt
microphone-sensitivity-medium-symbolic
multisystem-kiwi
battery-full-charged
weather-storm
multisystem-emmabuntus
bombono-dvd
gsm-3g-medium-secure
go-up-symbolic
cheese-take-burst
bonobo-component-browser
folder-symbolic
media-seek-backward-rtl
network-wired-symbolic
gnome-mime-application-x-deb
gtklpq
aptdaemon-action-resolving
banshee-panel
view-sidebar-symbolic
redhat-system_settings
printer-printing-symbolic
4137_winhlp32.0
redhat-filemanager
application-x-gnome-theme-package
send-to-symbolic
mail-private-symbolic
gtk-open
x-office-drawing-template
gtk-find-and-replace
application-ogg
mozilla-thunderbird
window_fullscreen
media-seek-forward-rtl-symbolic
application-x-sln
application-x-executable
printer-warning-symbolic
drive-harddisk
xfpm-primary-000-charging
gnome-mime-application-x-kword
multisystem-drop-blue
package-new
empathy-invisible
emblem-system
system-help
jockey-enabled
gnome-mime-application-vnd.oasis.opendocument.presentation-template
utilities-system-monitor-symbolic
multisystem-rosa
stock_file-properites
edit-clear-rtl-symbolic
face-angel-symbolic
chrome-gibkmnplhhipchonaiajhlchcpljekmj-Default
redhat-sound_video
folder-remote-ssh
stock_addressbook
notification-gpm-battery-020
notification-network-disconnected
nm-device-wired-autoip
preferences-desktop-keyboard-shortcuts
mythtv
openofficeorg3.0-impress
face-sad-symbolic
applications-microblogging-panel
gtk-properties
libreoffice-calc
easytag
multisystem-hiren
gramps
multisystem-gibraltar
sqliteman
nm-secure-lock
cups
go-jump-symbolic
gnome-robots
multisystem-save2
mail-mark-not-junk
gnome-fs-server
stock_text_italic
gnome-mime-application-x-archive
gpm-battery-020-charging
stew-gui
ooo-draw
pk-package-sources
text-xhtml+xml
preview-file
folder-publicshare-symbolic
applications-system
multisystem-nimblex
flashplayer
evolution-memos
kxkb
audio-card
partner
multisystem-saline
format-text-direction-ltr-symbolic
edittrash
multisystem-bs_BA
mdm
mail-reply-all
un-reboot
battery_empty
multisystem-avlinux
multisystem-goblinx
microphone-sensitivity-low
multisystem-klikit
multisystem-kaella
spreadsheet
mail-mark-unread
text-x-javascript
format-justify-left-symbolic
stock_smiley-22
libreoffice-presentation
package_games
nm-wwan-tower
emblem-music-symbolic
gtk-jump-to-rtl
template_source
chrome-bepbmhgboaologfdajaanbcjmnhjmhfn-Default
user-idle-symbolic
notification-gpm-battery-000
audio-input-microphone-symbolic
gnome-session-sleep
camera
ubuntuone-client-idle
format-text-direction-rtl-symbolic
gtk-directory
edit-delete
ok
pitivi
multisystem-resize
playonlinux
openofficeorg3-oasis-database
aptdaemon-action-waiting
nvidia-current-settings
gtk-goto-first-ltr
gnome-dev-removable-usb
application-vnd.oasis.opendocument.text-template
multisystem-linuxmint
libreoffice-oasis-spreadsheet-template
folder-downloads
multisystem-fa_IR
xfce-utils
gtk-missing-image
gnome-mime-application-x-python-bytecode
application-vnd.sun.xml.draw
gtk-media-previous-rtl
object-rotate-right
plasma
dropboxstatus-x
stock_left
text_bold
kfm_home
xfsm-switch
blueman-tray
softwarecenter
stock_mail-reply-to-all
playlist-automatic
multisystem-zxmame
battery-caution
audacious
xfce-wm-maximize
folder-remote
zoom-out
face-glasses
bookmarks_list_add
audio-volume-muted-blocking-panel
weather-clear-night
gnome-lockscreen
awn-settings
text-x-generic-symbolic
vnd.adobe.xfdf
light-green
stock_smiley-13
stock_smiley-18
pidgin-menu
insert-object
stock_smiley-15
stock_smiley-11
openterm
user-indeterminate
stock_smiley-10
network-wireless-encrypted
fileopen
application-msword
xfce-system-lock
notification-network-wireless-medium
multisystem-flip-vertical
virtualbox-vmdk
pppoeconf
gtk-save-as
multisystem-xpud
media-image
gnome-mime-application-vnd.oasis.opendocument.graphics
gnome-mime-application-x-gedcom
openshot
gtk-indent-rtl
stock_folder
gnome-mime-application-x-gramps
xfpm-battery-100-charging
none
dropboxstatus-busy2
gnome-mime-text-x-java-source
stock_calendar
2B5C_DigitalEditions.0
player_rew
ccc_large
gtk-clear
cheese
multisystem-ubuntugnome
mail-mark-important-symbolic
user-info
application-x-deb
gpm-primary-080-charging
x-office-drawing
achilles
file_new
multisystem-pebuilder
multisystem-gentoo
application-vnd.oasis.opendocument.presentation-template
multisystem-turbolinux
image-bmp
totem
application-vnd.oasis.opendocument.text
application-zip
cameramonitor
multisystem-estobuntu
media-jaz
player_play
view-sort-descending
gnome-mime-application-vnd.stardivision.calc
clamtk
xfce-system-exit
gnome-dev-pcmcia
eog
notification-battery-low
multisystem-easys
file-manager
folder-remote-smb
awf
ooo-calc3.0
multisystem-vector
application-x-backup
gnome-mime-application-x-tarz
lpi-bug
time-admin
application-x-msdownload
gnome-mime-application-vnd.sun.xml.calc
xfce4-ui
kate
presence_online
gwrite
notification-network-ethernet-disconnected
multisystem-quantian
radiotray
multisystem-gdata
user-bookmarks-symbolic
debug-kategdb
top
application-exit
gtk-cut
stock_weather-fog
gnome-mime-application-vnd.sun.xml.writer.template
skype_online
audio-input-microphone
system-restart-panel
gtk-media-next-ltr
nm-device-wireless
cyan
gnome-mime-image-x-cmu-raster
multisystem-gparted64
stock_new-tab
folder-download-symbolic
gdu-multidisk-drive
libreoffice3-math
audio-volume-medium
gpm-battery-100-charging
microphone-sensitivity-low-symbolic
gnome-mime-application-x-7zip
gproject-file
bluetooth-active-symbolic
battery-full-charged-symbolic
edit-select-symbolic
weather-indicator-unknown
network-wireless-signal-none-symbolic
channel-secure-symbolic
unknown
applications-accessories
stock_media-play
stock_mail-reply
folder_images
gtk-dialog-warning-panel
gtk-quit
users
media-seek-backward-symbolic
gtk-revert-to-saved-rtl
application-xfdf
folder-video-alt
audio-volume-off
multisystem-clearos
zoom-in
editcut
multisystem-eeebuntu
pino
qgis-mime
preferences-system-date-and-time-symbolic
text_under
xfpm-ups-000-charging
x-office-presentation-template
multisystem-debian
gnome-dev-ethernet
redhat-preferences
nm-tech-hspa
microphone-sensitivity-high
document-print
multisystem-anonymous-os
system-run
multisystem-chameleonos
xfce4-appfinder
gnome-display-properties
gnome-dev-media-memory
checkbox
audacity
network-cellular-signal-excellent-symbolic
multisystem-voyagerlivecd
browse-webcam-effects
gnome-screenshot
mail-attachment-symbolic
system-shut-down
document-page-setup
gtk-paste
format-text-strikethrough-symbolic
media-seek-forward-symbolic
multisystem-reactos
mono-runtime-common
gtk-preferences
ubuntuone-client-error
audio-volume-low-symbolic
bash
white
multisystem-mepis2
multisystem-puias
blue
gnomeradio
gnome-network-properties
ktip
multisystem-ubuntu-studio
xfce-wm-stick
multisystem-pelican
edit-find
preferences-desktop
avidemux-gtk
aptdaemon-add
gtk-justify-left
weather-few-clouds-night-350
package_office
battery-good-symbolic
gnome-dev-flashkey
application-rtf
drive-harddisk-root
alarm-clock
openofficeorg-base
security-medium-symbolic
application-vnd.ms-word.document.macroEnabled.12
catfish
gpm-primary-100
xfpm-primary-100
text-x-csrc
player_fwd
gdu-error
system-users-symbolic
go-last-symbolic
multisystem-display-properties
stock_lock-broken
multisystem-linex
notification-gsm-full
gnome-other
notification-battery-020-plugged
gnome-mime-text-x-copying
gnome-fs-blockdev
multisystem-toutou
gnome-mime-text-x-changelog
gnome-xterm
stock_help
weather-few-clouds-night-340
twitux
application-x-wine-extension-msp
multisystem-pureos
gnome-run
folder-open
podcast-new
multisystem-partition-wizard
network-error-symbolic
skype_dnd
rtmLogo
gnome-mime-application-x-zip
gnome-logo-icon-transparent
yast_HD
gimp
amarok
7596_iexplore.0
gnome-window-manager
application-vnd.openxmlformats-officedocument.spreadsheetml.sheet
multisystem-linuxgamers
light-cyan
alarm-clock-triggered
totem-tv
kcalc
multipart-encrypted
gnome-mime-application-fdf
stock_text_unindent
pirut
nm-signal-50-secure
application-vnd.adobe.adept+xml
weather-few-clouds-night-330
application-vnd.oasis.opendocument.presentation
wine-winecfg
emblem-generic
multisystem-livehacking
gnome-panel-launcher
face-angry-symbolic
knetattach
gnome-mime-image-x-psd
multisystem-calculate
multisystem-defender
multisystem-show
mail-message-new
multisystem-mandriva
ubuntuone-client-offline
face-cool
transmission-tray-icon
kradio4
multisystem-usbpen
deluge
multisystem-android
multisystem-connochaet
multisystem-ophcrack
weather-severe-alert-symbolic
system-software-install
face-wink
process-stop
multisystem-tuquito
multisystem-sr_CS
gdu-unmount
weather-few-clouds-night-320
gnome-mime-application-x-perl
kcmkwm
multisystem-ubcd4win
scanner
gnome-mime-application-x-compress
filesaveas
gnome-system-monitor
pidgin
0D54_Texts.0
dialog-information
gnome-mime-application-x-kpresenter
multisystem-liquidlemur
glade
kscreensaver
aptdaemon-action-removing
stock_leave-fullscreen
D19D_unins000.0
gdu-emblem-raid10
redhat-office
chrome-ijgoenplmfdccommlnocicpkjojfkkao-Default
edit-find-symbolic
gnome-dev-media-sm
gnome-power-manager
ppa
gnome-exe-thumbnailer-generic
computer-fail
application-certificate-symbolic
drive-harddisk-usb
xfce-terminal
lastfm
weather-few-clouds-night-310
application-x-note
tgz
foomatic-gui-logo
gnome-fs-directory-accept
sleep
gtk-recordmydesktop
face-sad
preferences-desktop-accessibility-symbolic
preferences-desktop-screensaver-symbolic
format-indent-more-symbolic
scanner-symbolic
im-message-new
gnome-web-browser
ooo-writer24
gnome-netstatus-error
folder
package-downgrade
zoom-in-symbolic
gnome-mime-application-x-javascript
user_auth
battery_caution
multisystem-geexbox
weather-clear-night-350
chrome-elkfjgffaejjneohochnpnefnigncpgi-Default
xfpm-suspend
gnome-settings-theme
gnome-do
call-end-symbolic
xfpm-battery-040-charging
gnome-glines
zoom-fit-best-symbolic
text-x-chdr
weather-few-clouds-night-300
libreoffice-oasis-drawing
network-wired
libreoffice-oasis-presentation-template
battery-full-symbolic
libreoffice-text-template
folders-publicshare
EasyTAG_icon
media-playback-start-rtl
application-x-ole-storage
ooo-impress3.0
insert-link
notification-gpm-battery-000-charging
gtk-dialog-warning
filenew
nm-stage03-connecting10
deluge-torrent
edit-undo
office-spreadsheet
application-default-icon
audio-volume-low-zero-panel
nm-stage03-connecting11
gnome-netstatus-50-74
gtk-go-back-rtl
bookmark-missing
gtk-unindent-ltr
emblem-favorite-symbolic
weather-clear-night-340
libreoffice-math
media-seek-forward-rtl
seahorse-preferences
stock_folder-properties
porthole
gnome-dev-floppy
WorldOfGoo
screensaver
transmission
notification-audio-volume-medium
gnome-dev-harddisk
process-stop-symbolic
user-bookmarks
gnome-cd
emblem-synchronizing
nm-stage03-connecting09
nm-stage03-connecting08
nm-stage03-connecting07
nm-stage03-connecting06
nm-stage03-connecting05
nm-stage03-connecting04
network-transmit
nm-stage03-connecting02
nm-stage03-connecting01
nm-stage03-connecting03
battery
xfpm-primary-020-charging
trashcan_full
gnome-mime-image-vnd.microsoft.icon
format-text-direction-rtl
multisystem-topologilinux
package-broken
multisystem-nst
dialog-question
weather-clear-night-330
xfce-trash_full
gnome-dev-disc-dvdrw
gnome-mime-text-x-zsh
gnome-settings-sound
blueman
xfce4_xicon
battery-good
xfce4-keyboard
appointment
gnome-activity-journal
redhat-server_settings
notification-network-wireless-disconnected
gnome-mime-image-bmp
truecrypt
start-here
openofficeorg-draw
multisystem-trisquel
gnome-mime-application-vnd.sun.xml.draw.template
multisystem-elive
gnome-dev-cdrom-audio
amazon-mp3-store-source
multisystem-paipix
note-16
mutt
classviewer-method
xfce4-menu-mint
system-users
weather-clear-night-320
multisystem-drop
gtklp
gpm-battery-040-charging
multisystem-diskcopy
gdu-category-multipath
application-x-wine-extension-its
gsm-3g-medium
freeciv-modpack
stock_mail-replied
face-monkey
stock_lock-ok
drakmenustyle
application-x-zip
gnome-session-hibernate
gtk-goto-last-ltr
gsd-xrandr
software-update-available-symbolic
multimedia-player-apple-ipod-touch
multisystem-gag
qemu-launcher-16x16
gdu-smart-unknown
multisystem-phinx
multisystem-slax
desktop-effects
weather-clear-night-310
nm-signal-25-secure
gnome-settings-background
stock_shuffle
media-player-banshee-panel
evince
empathy-extended-away
smplayer
gdu-smart-failing
bluetooth
xfpm-battery-080
multisystem-backtrack
gpm-battery-080
multisystem-vba
package_development
application-vnd.oasis.opendocument.drawing
ssh-askpass-gnome
stock_weather-showers
gnome-fs-home
emblem-unreadable
hardinfo
multisystem-pentoo
nepomuk
user-away-panel
package_wordprocessing
gnome-applications
rhythmbox-small
libreoffice-oasis-spreadsheet
gnome-dev-media-ms
emblem-important-symbolic
weather-clear-night-300
channel-insecure-symbolic
non-starred-symbolic
preferences-desktop-accessibility
multisystem-moonos
mail-mark-notjunk
gnome-shutdown
gsm-3g-high-secure
battery_full
media-optical
guayadeque
xfce4-panel-menu
multisystem-puppylinux
gdu-encrypted-lock
application-x-csproj
battery_two_thirds
gnome-aisleriot
exaile
tar
multisystem-lliurex
text-x-java-source
rhythmbox
gnome-mime-application-x-rpm
multisystem-pclinuxos
media-playlist-shuffle
oxygen
stock_text_center
application-x-m4
gnome-mime-application-x-font-linux-psf
stock_delete
help-contents
kde-windows
xfpm-battery-060
application-illustrator
gpm-battery-060
multisystem-igos
gtk-zoom-in
stock_terminal-showmenu
folder-templates-symbolic
system-file-progress-panel
bluetooth-disabled
gnome-mime-x-directory-smb-workgroup
mail-replied
stock_terminal-newwindow
application-x-cue
task-past-due
xfce-wm-unmaximize
multisystem-green
trophy-silver
multibootusb
find-location-symbolic
gnome-mime-text-x-install
multisystem-caixamagica
gloobus-preview
gnome-stock-mail-snd
gnome-status
stock_mail-unread
libreoffice3-writer
application-x-matroska
multisystem-redhat
multisystem-quirky
xfce4-workspaces
edit-undo-rtl
media-eject-symbolic
folders-music
text-html
ximian-evolution-calendar
playlist
drive-harddisk-ieee1394
messagebox_info
gnome-stock-text-unindent
call-missed-symbolic
gnome-dev-disc-dvdr
text-x-c
audio-x-mp3-playlist
x-office-document-template
xfsm-shutdown
gnome-mime-application-x-stuffit
xfm-battery-000
multisystem-biolinux
xfpm-battery-040
stock_new-text
gnome-mime-application-x-zim-notebook
gpm-battery-040
gnome-do-symbolic
text-x-credits
www
preferences-desktop-theme
multisystem-grub48
menu-editor
weather-severe-alert
audiocard
gtk-info
drakconf
application-x-7zip
applications-internet
mate-about-logo
block-device
light-blue
gnome-mime-application-vnd.oasis.opendocument.text-template
xfpm-primary-100-charging
multisystem-el_GR
locale
media-optical-dvd-rom
audio-x-generic-symbolic
gsm-3g-high
multisystem-red
face-uncertain
accessories-text-editor-symbolic
multisystem-abuledulive
bug-buddy
gloobus
sound-juicer
preferences-desktop-keyboard-shortcuts-symbolic
keyring-manager
multisystem-asri
empathy-offline
network-cellular-signal-none-symbolic
xfce-sound
start-here-debian
gnome-mime-text-vnd.wap.wml
software-update-urgent
multisystem-ubuntu-rescue-remix
iceweasel
add
irda
gnome-mime-application-x-audacity-project
multisystem-vortexbox
multisystem-cae
application-x-gnumeric
format-text-bold
text-css
gnome-mime-application-x-gnome-app-info
xfpm-battery-020
kfm-home
gpm-battery-020
object-flip-horizontal-symbolic
preferences-desktop-default-applications
gnome-dev-trash-full
gpodder
openofficeorg-writer
media-playback-pause-symbolic
back
vnd.oasis.opendocument.drawing
multisystem-nonfree
hp-logo
zoom-original
preferences-desktop-sound
multisystem-chrome
media-playback-start
application-x-scribus
multisystem-kaos
pdf
bluetooth-48
bitfling
multisystem-centos
multisystem-yoper
pda
x
multisystem-pardus
emblem-shared
chrome-emfinbmielocnlhgmfkkmkngdoccbadn-Default
multisystem-bluecherry
multisystem-astaro
gnome-fs-trash-full
multisystem-windows48
stock_up
stock_folder-copy
gtk-media-record
gnome-fs-bookmark-missing
system-log-out
audio-x-vorbis+ogg
libreoffice-startcenter
edit-select-all
drive-harddisk-symbolic
stock_mail-forward
multisystem-fuduntu
xfpm-ups-020-charging
xfpm-brightness-lcd-invalid
multisystem-icon
multimedia-player-apple-ipod
user-offline-symbolic
as-icon
view-grid-symbolic
multisystem-frugalware
libreoffice-main
package-x-generic-symbolic
folder-publicshare
multisystem-wattos
gnome-fs-trash-empty
novell-button
aptdaemon-working
dialog-password
libreoffice-presentation-template
multisystem-openIndiana
shotwell
minitunes
gpm-battery-000
ooo-calc
gnome-eterm
gnome-mime-application-x-compressed-tar
gpm-battery-charged
edit-clear
empathy-busy
emblem-downloads
document
multisystem-stresslinux
application-x-rpm
stock_print-preview
notification-network-wireless-high
multisystem-slitaz
nobody
gnome-dev-network
nm-signal-100-secure
multisystem-apple
gnome-dev-disc-audio
gnome-gmenu
face-crying
multisystem-ubcd
user-trash-symbolic
python2.7
multisystem-opengeu
gnome-dev-disc-cdrom
4288_utils.0
multisystem-drbl
font-x-generic
gnome-mime-application-x-executable
gnome-mime-application-x-lzma-compressed-tar
multisystem-kali
mail-send-symbolic
document-send-symbolic
gnome-fs-directory-visiting
cab_extract
text-x-bak
format-text-italic-symbolic
input-gaming-symbolic
tab-new-symbolic
libreoffice-oasis-presentation
application-vnd.oasis.opendocument.web-template
gnome-mime-application-vnd.oasis.opendocument.formula
xfpm-ac-adapter
ekiga
redhat-accessories
media-removable
microphone-sensitivity-medium
grass64
stock_weather-cloudy
text-plain
appointment-missed
emblem-favorite
gtk-close
gnome-mime-application-xml
help-about
applications-fonts
system-shutdown-panel-restart
important
gtk-zoom-out
application-javascript
gnome-term
dialog-error-symbolic
openofficeorg3.0-base
xfce-wm-unstick
multisystem-antergos
gnome-word
battery-empty-symbolic
fusion-icon-panel
gnome-dev-computer
stock_save-as
application-vnd.sun.xml.calc
xfwm4
xfce4-menueditor
uninterruptible-power-supply
mail-mark-junk
mail-forward
folder-saved-search
gnome-dev-flashdisk
B583_DITE.0
5D40_.0
multisystem-puredyne
gnome-note
gnome-lightsoff
xfce-games
gnome-volume-control
media-optical-cd-r
multisystem-aoss
edit-redo-rtl
gnome-dev-media-cf
pino-tray-icon-fresh
redhat-internet
freeciv-client
stock_new-dir
multisystem-ojuba
emblem-new
multisystem-finnix
shutter
system-floppy
system-hibernate
gnome-swell-foop
battery-good-charging
system-file-manager
light-red
gnome-dev-keyboard
dialog-warning
gnome-devel
multisystem-upstream
multisystem-ozunity
text-x-changelog
stock_internet
format-text-strikethrough
network-wired-acquiring-symbolic
format-indent-less-rtl
klipper
stock_thunar-shortcuts
emblem-desktop
tab_new
gnome-gnibbles
media-skip-forward-rtl-symbolic
application-atom+xml
gtk-floppy
multisystem-refind
cmake
gdu-smart-healthy
multisystem-pisilinux
media-player-banshee-buffering
user-images
multisystem-rox-filer
gtk-new
accessories-character-map-symbolic
multisystem-tr_TR
gnome-fs-nfs
fontforge
stock_search-and-replace
multisystem-blue
tab-new
gtk-strikethrough
utilities-terminal
chrome-aohghmighlieiainnegkcijnfilokake-Default
dvdstyler
presence_offline
gnome-mime-text-x-csh
Terminal
document-revert
list-remove-symbolic
edit-paste
gnome-dev-harddisk-usb
multisystem-konboot
multisystem-defragment
weather-few-clouds-night-symbolic
network-cellular-4g-symbolic
other-desktop
info
gnome-fs-executable
skype_na
accessibility-directory
gksu-icon
call-start-symbolic
multisystem-lite
font_bitmap
liferea
multisystem-hacao
multisystem-mageia
multisystem-linuxcoin
camera-web-symbolic
system-shutdown-symbolic
multisystem-drop-green
svg
gnome-mime-application-x-scribus
application-vnd.oasis.opendocument.database
audio-volume-muted-blocked-panel
multisystem-acronis
multisystem-ubunturescue
application-x-shockwave-flash
emblem-important
format-justify-left
appointment-soon-symbolic
multisystem-ulite
security-high-symbolic
notification-battery-100
xfpm-battery-060-charging
object-flip-vertical
media-optical-audio
gnome-session-suspend
brown
gtk-media-forward-ltr
font
stock_terminal-compose
gtk-go-forward-ltr
package-installed-locked
font_type1
dockbarx
ubuntuone
gohome
notification-gpm-battery-020-charging
gnome-mime-application-x-class-file
insert-image
start-here-opensuse
multisystem-dreamLinux
multisystem-uknow4kids
gnome-fs-ftp
multisystem-thinstation
indicator-applet
nm-signal-0
multisystem-webconverger
gnome-mime-application-vnd.openxmlformats-officedocument.presentationml.presentation
audio-volume-medium-symbolic
folders-downloads
go-last
notification-battery-060-plugged
gdu-raid-array
ubuntu-logo
multisystem-saxenos
multisystem-elastix
ooo-writer
multisystem-beakos
bitpim
gnome-mime-text-x-source
gnome-graphics
go-last-rtl
classviewer-member
document-save-as
multisystem-archbang
multisystem-freedos
glom
process-working
x-office-spreadsheet-template
kwin
gnome-mime-text-html
xfpm-primary-040-charging
gnucash-icon-32x32
gnome-netstatus-idle
text-x-python
multisystem-swift
multisystem-caine
gdu-emblem-raid6
ksysguard
aptdaemon-action-downloading
media-flash-ms
preferences-desktop-peripherals
application-text
spotify
multisystem-tinycore
appointment-missed-symbolic
multisystem-edubuntu
gnome-mime-application-x-rar
gpm-primary-080
cupsprinter
view-fullscreen
folder-documents
xfpm-primary-080
kradio
gnome-mime-text-x-authors
gsm-3g-none-secure
window-close
multisystem-hi_IN
media-memory-sm
gdu-emblem-raid5
package-reinstall
2EF4_wordpad.0
gproject-follow
stock_paste
thinderbird-icon
battery-full-charging
mail_send
media-memory-sd
openofficeorg3.0-draw
gdu-emblem-raid4
application-x-theme
stock_search
gnome-mime-video
blueradio-48
gmail
gdu-emblem-raid3
gpm-battery-060-charging
gdu-emblem-raid1
gdu-raid-array-start
gdu-emblem-raid0
battery-low-symbolic
kynpatic
stock_terminal-newtab
stock_copy
E340_ClockIt-Online.0
kcontrol
alarm-timer
redhat-network-server
network-transmit-symbolic
call-stop
player_record
yast_mouse
multisystem-inquisitor
emblem-photos
stock_media-next
freeciv-server
preferences-desktop-multimedia
nm-device-wired
network-cellular-edge-symbolic
gdu-raid-array-stop
battery-caution-symbolic
image-x-psdimage-x-psd
preferences-other-symbolic
document-open-recent-symbolic
gdm-setup
multisystem-toorox
multisystem-upr
text-x-script
text-x-copying
extension
openofficeorg3-oasis-spreadsheet
gtk-zoom-100
xfpm-primary-060
gpm-primary-060
x-system-software-sources
bt-logo
help-browser
gtk-go-down
preferences-sound
system-upgrade
media-optical-dvd-ram
keyboard-brightness-symbolic
image-x-win-bitmap
gdebi
error
gnome-dev-disc-dvdr-plus
gnome-dev-unknown-usb
plip
multisystem-bridge
multisystem-ubuntukylin
stock_appointment-reminder
multisystem-peppermint
media-eject
preferences-desktop-display-symbolic
image-png
package_utilities
mime_ascii
nm-vpn-standalone-lock
gnome-mime-application-vnd.oasis.opendocument.text-web
multisystem-minix
media-playlist-shuffle-symbolic
drakstats
multimedia-player-ipod
yast_printer
multisystem-superos
gnome-session-logout
face-sick
editdelete
audio-mpeg
image-jpeg
gmailwatcher
weather-few-clouds-night-290
gtk-help
multisystem-privatix
xchat-panel
xfce4-dict
filequickprint
format-indent-more-rtl-symbolic
multisystem-systemrescue
multisystem-majilux
multisystem-slampp
kuser
gnome-log-out
multisystem-dreamstudio
AdobeReader10
xfpm-primary-040
multisystem-greenie
gpm-primary-040
multisystem-commodore
object-flip-vertical-symbolic
system-suspend
format-justify-center-symbolic
multisystem-parsix
gnome-sound-recorder
gnome-mime-application-x-applix-word
multisystem-opensuse
pithos
media-skip-forward
openofficeorg3.0-template
arts
multisystem-flip-horizontal
gdu-smart-threshold
camera-web
weather-few-clouds-night-280
gnome-mime-application-x-gnome-theme-package
gnome-mime-text-x-makefile
HPmenu
multisystem-incognito
multisystem-proxmox
multisystem-linuxxp
multisystem-insert
trophy-bronze
gnome-netstatus-txrx
stock_cut
multisystem-kubuntu
gtk-yes
openofficeorg-printeradmin
973D_ClockItDirect.0
emblem-documents-symbolic
stock_text_left
notification-gpm-battery-100-charging
gdu-info
spotify-client
multisystem-slackware
gnome-mime-image-vnd.adobe.photoshop
gnome-settings
gnome-mime-application-msword
ibus
lastfm-audioscrobbler
jockey-certified
user-share
applications-engineering
weather-few-clouds-night-270
gnome-mime-application-vnd.sun.xml.writer
system-lock-screen
network-vpn-symbolic
edit-undo-symbolic
viewmag1
multisystem-ubuntu
face-smirk
viewmag-
ndisgtk-error
viewmag+
camera-video
xfpm-primary-020
user-invisible-panel
gpm-primary-020
stock_file-properties
face-devilish
document-save
gnome-mime-x-font-afm
document-send
xfpm-primary-missing
gnome-stock-trash
mail_forward
multisystem-bsd
application-x-compress
web-browser-symbolic
gtk-bold
gsm-3g-low
media-skip-backward-rtl-symbolic
weather-few-clouds-night-260
xterm_32x32
gnome-mime-application-vnd.oasis.opendocument.spreadsheet
application-x-rar
dropbox
start-here-frugalware
usb-creator-gtk
application-vnd.scribus
ooo-writer2
gnome-logout
text-x-c++src
gdu-detach
multisystem-macpup
zoom-fit-best
gnome-mime-text-x-vcalendar
multisystem-madbox
jockey-proprietary
libreoffice-impress
gnome-mime-application-x-cpio-compressed
go-first-symbolic
edit-delete-symbolic
wxmaxima-32
notification-gsm-medium
nm-device-wwan
software-properties
battery-full
gnome-about-logo
BFE9_Demo.0
gnome-tali
weather-few-clouds-night-250
list-add-symbolic
rhythmbox-panel
stock_thunar-templates
multisystem-abuledu
stock_media-pause
monodevelop
application-octet-stream
vcalendar
libreoffice-writer
gtk-media-pause
xfpm-primary-000
gpm-primary-000
evolution-tasks
ooo-math
green
yast_soundcard
stock_redo
action-unavailable-symbolic
multisystem-leeenux
multisystem-asturix
calc
multisystem-avira
multisystem-vbox
gnome-mime-application-x-geneweb
multisystem-pear
weather-clear-night-290
stock_mail-compose
non-starred
weather-few-clouds-night-240
video-x-generic
stock_properties
network-cellular-connected-symbolic
start-here-symbolic
applications-other
mplayer
audio-volume-high-panel
text-x-generic-template
gnome-mime-text
gnome-desktop-config
gnome-power-manager-symbolic
flegita
multisystem-venenux
xfpm-ups-040-charging
mail-read
dia
mail-mark-read
source-smart-playlist
dark-gray
multisystem-linpus
xfsm-hibernate
file-roller
tvm-burn-cd
weather-clear-night-280
multisystem-liberte
multisystem-bayanihan
weather-few-clouds-night-230
multisystem-uhu
gedit-icon
help-browser-symbolic
gnome-fs-trash-empty-accept
weather-showers-symbolic
gtk-justify-center
stock_folder-move
swirl-foot
media-flash-cf
misc
image-tiff
application-vnd.ms-excel
libreoffice-oasis-web-template
multisystem-kongoni
ED5E_uninstall.0
classviewer-macro
multisystem-wifislax
network-wired-disconnected-symbolic
htop
weather-clear-night-270
battery_charged
media-cdrom-audio
plan
weather-few-clouds-night-220
gnome-dev-jazdisk
miro
libreoffice-oasis-text
media-optical-audio-new
image-svg+xml
gnome-spinner
stock_unknown
mail-read-symbolic
xfce-wm-minimize
nm-vpn-active-lock
weather-few-clouds
susehelpcenter
multisystem-ylmf
ooo-calc24
format-indent-more
libreoffice3-impress
wxmaxima-16
cdwriter_unmount
blender
chrome-ejjicmeblgpmajnghnpcppodonldlgfn-Default
session-properties
text-x-c++hdr
folder-videos-symbolic
stock_zoom-in
empathy
weather-clear-night-260
gnome-dev-wavelan-encrypted
weather-few-clouds-night-210
package-installed-outdated
gtk-leave-fullscreen
boot
system-suspend-hibernate
text-x-java
stock_lock
multisystem-pfsense
ndisgtk
gdu-unmountable
weather-few-clouds-night-200
multisystem-hanthana
format-justify-right-symbolic
gnome-settings-accessibility-technologies
gtk-media-rewind-ltr
messagebox_warning
gtk-apply
face-smile
drive-removable-media
network-vpn
gnome-remote-desktop
help
stock_volume-mute
virtualbox
gdu-category-multidisk
weather-clear-night-250
edit-add
html
acroread
applications-office
emblem-urgent
stock_new-address-book
computer
gtk-cancel
contact-new
text-x-install
multisystem-partedmagic
logview
preferences-system-windows
nm-signal-75-secure
Scrivener
inkscape
gnome-mime-application-x-cpio
deb
multisystem-catix
unison-gtk
utilities-terminal-symbolic
akregator
weather-clear-night-240
chromium-browser
access
image-x-generic
multisystem-ploplinux
gnome-fs-share
python
xterm-color_48x48
BBE2_msiexec.0
multisystem-momonga
gsm-3g-low-secure
biogenesis
keyboard
openttd
multisystem-aptosid
network-wireless-encrypted-symbolic
user-desktop
multisystem-ultimate-edition
scrivener
package-manager-icon
aptdaemon-upgrade
application-fdf
dialog-question-symbolic
weather-clear-night-230
battery-good-charging-symbolic
ooo-impress24
document-open-recent
media-tape
changes-allow
openofficeorg24-impress
multimedia-volume-control
libreoffice-template
editclear
bookmark-new
application-7zip
start-here-linux-mint
network-wired-disconnected
network-cellular-3g-symbolic
zoom-best-fit
weather-indicator-error
nohost
addressbook
multisystem-Kaspersky
stopwatch
application-x-compressed-tar
gnome-mime-image-png
preferences-desktop-remote-desktop
amule
gnome-mime-application-vnd.oasis.opendocument.spreadsheet-template
multisystem-turnkey
docky
weather-clear-night-220
object-rotate-right-symbolic
multisystem-qimo
multisystem-scientificLinux
network-receive-symbolic
text-x-c++
multisystem-sidux
xfpm-battery-080-charging
multisystem-netbootme
gnome-mime-application-x-jar
text_italic
multisystem-blag
gnome-mime-application-x-ruby
multisystem-magic
language-selector
emblem-shared-symbolic
multisystemblender-boot
krb-valid-ticket
user-away-symbolic
network-cellular-gprs-symbolic
network-wireless
network-error
stock_print-setup
zoom-out-symbolic
gtk-goto-first-rtl
notification-gpm-battery-040-charging
krb-expiring-ticket
stock_text_justify
go-next-rtl-symbolic
kcharselect
config-date
gnome-quadrapassel
weather-clear-night-210
activity-log-manager
face-tired
multisystem-distrowatch
stock_zoom-out
multisystem-kanotix
office-writer
monitor
multisystem-skolelinux
ghex
input-tablet
multisystem-zevenos
face-raspberry
stock_text_bold
stock_home
face-kiss
player_end
notification-gpm-battery-empty
stock_printers
media-player-banshee
gnome-stock-mail-rpl
jockey-kde
multisystem-tanglu
rhythmbox-symbolic
weather-clear-night-200
folder-remote-nfs
scribus
podcast
application-rss+xml
gnome-phone-manager
notification-audio-volume-low
xfpm-primary-060-charging
notification-gsm-none
help-faq
multisystem-handylinux
gcr-key-pair
reload_all_tabs
text-x-generic
xfce-wm-menu
application-x-sqlite3
application-x-sqlite2
multisystem-iboot
stock_media-prev
gnome-mime-application-pdx
face-surprise
multisystem-lubuntu
mail_replyall
window_nofullscreen
network
virtualbox-ovf
picard
gproject-header
folder-pictures
printer-symbolic
nm-signal-100
gcolor2
paprefs
editcopy
revert
stock_dialog-error
gnome-mime-application-pdf
audio-x-ms-wma
Thunar
light-magenta
virtualbox-ova
multisystem-blackpanther
wine-uninstaller
thunderbird
network-transmit-receive-symbolic
avatar-default-symbolic
user-offline-panel
application-vnd.openxmlformats-officedocument.wordprocessingml.document
gpm-battery-080-charging
multisystem-frenzy
gnome-mime-application-javascript
multisystem-bachatalinux
TagTool
gparted
preferences-desktop-wallpaper-symbolic
gnome-globe
gproject-collapse
multisystem-ubuntu_secured_remix
gnome-dev-removable
stock_help-add-bookmark
as-powered
gnome-fs-network
reload3
editpaste
gnome-mime-image-x-portable-bitmap
folder-remote-ftp
libpeas-plugin
picard-24
virtualbox-hdd
mail-mark-important
gnome-session-reboot
sticky-notes
stock_mail-send-receive
audio-x-adpcm
gnome-character-map
stock_mail-send
inode-directory
application-vnd.oasis.opendocument.text-web
background
internet-news-reader
sound
multisystem-id_ID
xfpm-ups-charged
message
stock_close
user-busy-symbolic
picard-32
preferences-desktop-wallpaper
xfce-trash_empty
view-list-symbolic
gpm-primary-000-charging
soundconverter
nm-vpn-connecting13
redhat-home
gnome-dev-printer-network
nm-no-connection
weather-overcast
gnome-dev-harddisk-1394
tasque
package-x-generic
application-x-bittorrent
xscreensaver
edit-copy-symbolic
gdu-emblem-raid-linear
preferences-desktop-font
multisystem-xiaopan
edit-redo-symbolic
tasque-32
openofficeorg3-base
gnome-mime-application-vnd.ms-powerpoint
bluefish-icon
multisystem-zencafe
aptdaemon-wait
rhythmbox-set-star
battery-low-charging
7AA0__2BFD57D817C074C3880EB7.0
picard-22
tasque-48
format-text-bold-symbolic
gtk-media-next-rtl
gtk-go-up
extract-archive
view-refresh-symbolic
package_network
multisystem-berry
picard-16
virtualbox-ose
nm-tech-3g
stock_down
multisystem-linutop
multisystem-kororaa
dialog-error
multisystem-elementary
stock_weather-sunny
image-x-svg+xml
player_stop
multisystem-smeserver
application-vnd.openxmlformats-officedocument.spreadsheetml.template
battery-caution-charging
multisystem-alpine
multisystem-linuxfx
text-enriched
openofficeorg3-writer
nm-vpn-connecting12
dconf-editor
stock_spellcheck
media-playlist-repeat-symbolic
emesene
mail_spam
drive-harddisk-scsi
redhat-programming
f-spot
face-angry
accessories-text-editor
gtk-select-all
go-next-rtl
user-idle-panel
notification-battery-080
nm-vpn-connecting14
font_truetype
application-x-jar
go-up
xfce-system
media-optical-dvd-rw
nm-vpn-connecting11
nm-vpn-connecting10
notification-battery-empty
nm-tech-edge
mdmflexiserver
mail-sent
application-vnd.openxmlformats-officedocument.presentationml.template
multimedia
multisystem-qemu
gtg
touchpad-disabled-symbolic
chrome-ildkhammdcmhddldkcjgkencmonoanfg-Default
nm-tech-umts
xfce4-notifyd
nm-vpn-connecting09
system
stock_zoom-1
nm-vpn-connecting06
battery_plugged
security-low
gnome-stock-text-indent
mail-send
media-dvd
emblem-default
nm-vpn-connecting08
nm-vpn-connecting02
nm-vpn-connecting07
nm-vpn-connecting05
nm-vpn-connecting04
nm-vpn-connecting01
nm-vpn-connecting03
magnatune
deluge-panel
battery-empty-charging-symbolic
synaptic
system-shutdown-panel
tasque-24
meld
gnome-dev-wavelan
stock_media-stop
multisystem-nutyx
gnome-netstatus-25-49
application-x-python-bytecode
internet-web-browser
folder-video
multisystem-arios
tasque-22
system-help-symbolic
input-dialpad-symbolic
libreoffice-spreadsheet-template
audio-volume-high
lpi-translate
media-skip-backward-rtl
wikipedia
bluetoothradio
notification-battery-060
stock_dialog-question
application-vnd.ms-powerpoint
user-offline
folder-templates
skype
application-x-gnome-saved-search
gnome-dev-battery
stock_new-window
package-remove
xfpm-battery-charged
system-config-printer
weather-showers-scattered
network-offline
application-x-7z-compressed
xfapplet2
tasque-16
geany
xfpm-keyboard-100
video
multisystem-chakra
emblem-documents
xfce4-splash
gdeb
multisystem-vine
centrejust
stock_stop
nvidia-settings
multisystem-draco
openofficeorg-math
xfapplet1
stock_save
notification-battery-000-plugged
games-endturn
preferences-desktop-keyboard
weather-showers-scattered-symbolic
applications-graphics
stock_weather-night-few-clouds
user-home
gtk-harddisk
folder_new
xfce-wm-close
gcr-key
jedit
application-vnd.ms-powerpoint.presentation.macroEnabled.12
mysql-workbench
style
multisystem-exe
emblem-system-symbolic
network_fs
aptdaemon-delete
xfce-unknown
cheese-take-photo
folder-new
notification-battery-040
yumex
gtk-about
shutter-panel
ooo-draw3.0
gnome-nettool
stock_smart-playlist
multisystem-notalinux
gnome-glchess
notification-network-ethernet-connected
modem
application-x-archive
gnome-sudoku
zip
gnome-mime-text-x-readme
adobe-flashplayer
zim
internet-radio-new
stock_insert-note
application-x-trash
mail-replies-symbolic
gtk-goto-top
xfsm-logout
defcon
xfpm-ups-060-charging
gconfeditor
gnome-mime-image-x-xpixmap
device-notifier
mousepad
chardevice
kentoo
multisystem-aldos
microphone-sensitivity-muted
text_strike
view-refresh
xfsm-suspend
security-medium
multisystem-hide
comix
start-here-mandriva
zoom-fit
openofficeorg3.0-calc
gnome-mime-application-x-bzip
gksu
openofficeorg3-draw
terminal
chrome-aknpkdffaafgjchaibgeefbgmgeghloj-Default
gnome-dev-ipod
multimedia_section
multisystem-kepler
ubuntuone-client
go-down-symbolic
multisystem-manjaro
gpk-repo
multisystem-dban
gnome-mime-application-x-killustrator
gnome-mime-audio
gtk-print
evolution
notification-battery-020
gnome-info
gnome-foot
eclipse
skype_away
tvm-dev-pocketpc
emblem-default-symbolic
kfm
multisystem-vinux
xfpm-brightness-lcd
preferences-system
gsm-3g-full
gnome-mime-application-x-applix-spreadsheet
gtk-copy
gnome-ccdesktop
media-optical-data-new
notification-gsm-low
gnome-mime-text-x-csharp
multisystem-tux
multisystem-img
gnome-mime-application-atom+xml
text-spreadsheet
preferences-desktop-screensaver
folder_pictures
aptdaemon-cleanup
visualization
multisystem-biglinux
gnome-klotski
mail-inbox
korgac
browser-help
audio-x-wav
application-vnd.rn-realmedia
folder-recent
messagebox_critical
gtk-dialog-info
stock_dialog-info
unknown-channel
preferences-desktop-locale
user-busy
user-available
display-capplet
camera-photo
openofficeorg3-printeradmin
aptoncd
multisystem-cdrom
multisystem-cinnarch
desktop
multisystem-crunchbang
window-close-symbolic
applications-science-symbolic
gnome-gnect
phone-symbolic
gtk-unindent-rtl
notification-battery-000
multisystem-alinux
multisystem-chameleon
stock_shared-by-me
nm-stage01-connecting11
nm-stage01-connecting10
python3
user-available-symbolic
ooo-template
gnome-util
preferences-system-firewall
kde
network_local
image-x-icon
gnome-mime-application-vnd.openxmlformats-officedocument.spreadsheetml.sheet
application-xml
multisystem-kwort
bleachbit
openofficeorg-calcooo-draw
gnome-modem
gnome-fs-desktop
fusion-icon-symbolic
ascii
nm-stage01-connecting09
nm-stage01-connecting08
nm-stage01-connecting07
nm-stage01-connecting06
nm-stage01-connecting05
nm-stage01-connecting04
nm-stage01-connecting03
nm-stage01-connecting02
nm-stage01-connecting01
emblem-nowrite
fillets-ng
source-playlist
image-x-eps
face-smile-symbolic
jdownloader
config-users
application-x-mint
libreoffice-drawing-template
face-plain
folders-documents
vlc
printmgr
notification-network-wireless-full
gnome-system
application-x-ruby
multisystem-tl
yast_idetude
redhat-graphics
gtk-dialog-question
multisystem-imagineos
E72E_ClockIt.0
google-earth
mail-signed
wordprocessing
dialog-apply
multisystem-stella
multisystem-riplinux
input_devices_settings
multimedia-player
gmdb2
gtk-goto-last-rtl
gtg-panel
mail-replied-symbolic
user-home-symbolic
jockey-disabled
xfce4-indicator-plugin
multisystem-sk
multisystem-splash-prevue
network-workgroup-symbolic
midori
gdu-hba
edit-cut-symbolic
format-text-underline-symbolic
battery-empty
pino-tray-icon
folder-images
printer
gnome-settings-mouse
gnome-mines
multisystem-freespire
text-editor
stock_volume-0
multisystem-wolvix
gnome-desktop-item-edit
debian-logo
multisystem-sparkylinux
multisystem-ru
multisystem-ro
address-book-new
multisystem-ubuntuce
gnome-stock-mail-fwd
go-jump
stock_terminal-closetab
media-optical-dvd
network-transmit-receive
applets-screenshooter-symbolic
xfce-printer
media-record-symbolic
xfce-wm-shade
notification-gpm-battery-060-charging
multisystem-doudoulinux
gnome-iagno
gdm-xnest
ooo-template3.0
emblem-mail
libreoffice-text
ipod_mount
view-restore-symbolic
wine-winetricks
openofficeorg3-template
add-files-to-archive
devede
object-rotate-left-symbolic
folder_home
multisystem-odebian
gnome-panel
multisystem-pt
multisystem-avg
multisystem-untangle
gnome-fs-regular
multisystem-kodi
multisystem-arch
joystick
multisystem-nosonja
package-installed-updated
virtualbox-vbox-extpack
gnome-dev-dvd
gnome-stock-mail-new
xfpm-primary-080-charging
vlc-xmas
text-x-sql
multisystem-xen
blueradio
emblem-photos-symbolic
rpm
media-playback-stop-symbolic
face-angel
multisystem-trinity
multisystem-comfusion
gtk-media-play-ltr
gtk-fullscreen
last-fm
finish
libreoffice3-template
multisystem-netsecl
multisystem-gnome
3floppy_unmount
multisystem-pl
gnome-mime-application-vnd.openxmlformats-officedocument.wordprocessingml.document
gnome-dev-cdrom
folder-saved-search-symbolic
office-address-book
weather-few-clouds-night-190
stock_playlist
image-jpeg2000
add-folder-to-archive
gtk-undo-ltr
network-server
stock-refresh
gnome-stock-mic
multisystem-nl
gnome-dev-disc-cdr
image-missing
application-vnd.ms-access
edit-clear-symbolic
image-x-ico
call-start
format-text-underline
multisystem-download
media-optical-dvd-r-plus
googleearth
covergloobus
multisystem-solydxk
multisystem-musix
libreoffice3-printeradmin
locked
connect_established
gdu-category-peripheral
application-vnd.oasis.opendocument.spreadsheet
multisystem-Sn0wL1nuX
jockey-free
applications-utilities-symbolic
gnome-mime-text-x-csrc
audio-volume-zero-panel
avidemux
changes-prevent-symbolic
multisystem-pinguy
view-sort-ascending
server
gnome-netstatus-disconn
khelpcenter
applications-engineering-symbolic
multisystem-no
gtk-sort-ascending
stardict
video-display-symbolic
mail-unread
application-x-class-file
locationbar-erase
folder-videos
abrt
samba
skype_offline
image-x-xcf
distributor-logo
image-x-psd
office-illustration
mail_reply
gpm-primary-020-charging
gnome-dev-disc-dvdrom
seahorse
folder-download
avatar-default
gkdebconf-icon
preferences-desktop-personal
weather-few-clouds-night-170
deluge-torrent-panel
gnome-eog
classviewer-var
gtk-dialog-authentication-panel
xfce4-panel
input-dialpad
stock_attach
multisystem-likinux
gdm
xfce_unknown
document-open
multisystem-mythdora
multisystem-drop-red
media-optical-cd-rw
yellow
multisystem-dynebolic
gtk-jump-to-ltr
multisystem-ipredia
application-vnd.oasis.opendocument.graphics
audio-volume-medium-panel
printer1
multisystem-linhes
multisystem-lv
x-office-spreadsheet
stock_repeat
network-cellular-acquiring-symbolic
multisystem-suse
network-wireless-signal-good-symbolic
multisystem-ta_IN
weather-few-clouds-night-160
system-software-update
multisystem-openartist
gnome-mime-application-vnd.ms-excel
wine
multisystem-debris
multisystem-virtualbox
modem-manager
next
user-pictures
multisystem-kdemar
ntm
xfce-system-info
stock-home
qemu-launcher
gdu-expander
gnome-mime-application-x-ms-dos-executable
gnome-mime-x-directory-nfs-server
go-next
gtk-media-previous-ltr
libreoffice-formula
rotate
kfind
gnome-mime-application-x-gzip
stock_trash_full
openofficeorg24-calc
nm-stage02-connecting11
nm-stage02-connecting10
gnucash-icon
multisystem-epidemic
empathy-away
gnome-exe-thumbnailer-generic-x
weather-few-clouds-night-150
system-file-manager-panel
media-skip-forward-symbolic
ooo-base3.0
application-mbox
media-floppy
drive-removable-media-ieee1394
logviewer
gdu-warning
chrome-ooccbihjbmlnodaodcfpghekjmpohgnl-Default
media-playback-stop
go-previous-rtl
drive-cdrom
audacious-panel
stock_new-appointment
gnome-sticky-notes-applet
stock_undo
nm-stage02-connecting09
nm-stage02-connecting08
nm-stage02-connecting07
nm-stage02-connecting06
nm-stage02-connecting05
nm-stage02-connecting04
nm-stage02-connecting03
nm-stage02-connecting02
nm-stage02-connecting01
starred-symbolic
system-config-date
format-justify-fill-symbolic
weather-clear-night-190
multisystem-salix
stock_weather-night-clear
weather-few-clouds-night-140
emptytrash
}

{$ENDIF}
end.

